# Generated by Django 5.2.8 on 2025-12-04 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_timelineevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineevent',
            name='related_company',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='related_contact',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='related_deal',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='related_task',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.company'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.contact'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.deal'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
