# Generated by Django 5.2.8 on 2025-12-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
    ]
