# Generated by Django 5.2.8 on 2025-12-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_note_options_note_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='company',
        ),
        migrations.RemoveField(
            model_name='note',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='note',
            name='deal',
        ),
        migrations.AlterField(
            model_name='note',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tasks.task'),
        ),
    ]
