# Generated by Django 5.2.8 on 2025-12-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_note_company_remove_note_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
